In [1]:
import numpy as np
import cv2

In [2]:
def findCircles(frame):
    # Convert to grayscale
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    # Blur the image to reduce noise
    gray = cv2.GaussianBlur(gray, (5, 5), 0)
    # Apply the Hough Transform to find circles
    circles = cv2.HoughCircles(gray, cv2.HOUGH_GRADIENT, 1, 20, param1=50, param2=70, minRadius=5, maxRadius=200)
    if circles is not None:
        circles = np.uint16(np.around(circles))
        for i in circles[0, :]:
            # Draw the outer circle
            cv2.circle(frame, (i[0], i[1]), i[2], (0, 255, 0), 2)
            # Draw the center of the circle
            cv2.circle(frame, (i[0], i[1]), 2, (255, 0, 0), 3)

    cv2.imshow("Webcam", frame) # This will open an independent window
    return circles

In [3]:
def recognizeRed(frame):
    # Convert BGR to HSV
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    # Define range of red color in HSV
    lower_red = np.array([-10, 50, 50])
    upper_red = np.array([10, 255, 255])
    # Threshold the HSV image to get only red colors
    mask = cv2.inRange(hsv, lower_red, upper_red)
    # Bitwise-AND mask and original image
    res = cv2.bitwise_and(frame, frame, mask=mask)
    cv2.imshow("Filtered", res) # This will open an independent window
    return res

In [4]:
def maskCircle(res, center, radius):
    # Create a black mask with the same shape as the image
    mask = np.zeros_like(res)

    # Create a white circle on the mask
    cv2.circle(mask, center, radius, (255, 255, 255), -1)

    # Apply the mask to the image
    masked_image = cv2.bitwise_and(res, mask)

    # cv2.imshow("Masked", masked_image) # This will open an independent window

    # cv2.waitKey(0)

    return masked_image

In [5]:
def countRedPixels(res, circles):
    counts=np.array([])

    # Created a mask for each circle
    for circle in circles[0, :]:
        center = (circle[0], circle[1])
        radius = circle[2]
        masked_image = maskCircle(res, center, radius)
        #cv2.imshow("Masked", masked_image) # This will open an independent window

        gray_masked_image = cv2.cvtColor(masked_image, cv2.COLOR_BGR2GRAY)
        
        # Count the number of non-black pixels
        count = cv2.countNonZero(gray_masked_image)
        counts = np.append(counts, count)

        #print(count)
        #cv2.waitKey(0)
    
    return counts

In [6]:
def findMostRedCircle(counts, circles):
    # Find the circle with the most red pixels per area
    radii = circles[0, :, 2]
    max_index = np.argmax(counts/radii**2)
    max_circle = circles[0, max_index]
    #print(max_circle)
    #cv2.waitKey(0)
    return max_circle

In [7]:
def recognizeOOI(cap):
    success, frame = cap.read()

    circles=findCircles(frame)

    if circles is not None:
        #print(circles)
        res = recognizeRed(frame)
        counts = countRedPixels(res, circles)
        max_circle = findMostRedCircle(counts, circles)
        #print(max_circle)
        #print('\n')
        return max_circle
    
    return None

In [8]:
def circleInFieldOfRegard(ref_circle, circles):
    # Get the dimensions of the field of regard
    maxdist=20

    # Get the coordinates of the ref_circle
    xref = ref_circle[0]
    yref = ref_circle[1]

    goodcircles = np.copy(circles)

    #print(circles)
    i=0
    delindex = []

    for circle in circles[0, :]:
        x = circle[0]
        y = circle[1]
        if (xref-x)**2+(yref-y)**2>maxdist**2:
            #print((xref-x)**2+(yref-y)**2)
            delindex.append(i)
        i+=1

    goodcircles = np.delete(goodcircles, delindex, axis=1)

    if(goodcircles.size==0):
        return None

    #print(goodcircles)
    #print(circles)
    #cv2.waitKey(0)
    return goodcircles

In [9]:
def trackOOI(ref_circle, cap):
    # # Create a VideoCapture object
    # cap = cv2.VideoCapture(0)

    lastcircle = ref_circle
    failcount = 0
    max_circle = None

    while True:
        # Capture frame-by-frame
        success, frame = cap.read()

        max_circle = None

        circles=findCircles(frame)

        if circles is not None:
            #print(circles)
            goodcircles = circleInFieldOfRegard(lastcircle, circles)
            if goodcircles is not None:
                #print("if")
                res = recognizeRed(frame)
                counts = countRedPixels(res, goodcircles)
                max_circle = findMostRedCircle(counts, goodcircles)           
                #print('\n')
                lastcircle= max_circle
                failcount = 0
            else:
                #print("else")
                failcount += 1
                print(failcount)
                if failcount>10:
                    break
        else:
            failcount += 1
            print(failcount)
            if failcount>10:
                break
        
        #print(failcount)
        print(max_circle)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break


In [10]:
cap = cv2.VideoCapture(0)
cap.set(3,640) # adjust width
cap.set(4,480) # adjust height

while True:
    #success, img = cap.read()

    # Do some processing on the image here (using opencv) - inspiration below:
    # https://www.geeksforgeeks.org/detect-an-object-with-opencv-python/
    # https://docs.opencv.org/4.x/da/d53/tutorial_py_houghcircles.html

    print("Recognizing OOI")

    max_circle=recognizeOOI(cap)

    print(max_circle)

    if max_circle is not None:
        print("Tracking OOI")
        # print(max_circle)
        # print('\n')
        # cv2.waitKey(0)
        trackOOI(max_circle, cap)
        
    #cv2.imshow("Webcam", img) # This will open an independent window
    if cv2.waitKey(1) & 0xFF==ord('q'): # quit when 'q' is pressed
        cap.release()
        break
        
cv2.destroyAllWindows() 
cv2.waitKey(1) # normally unnecessary, but it fixes a bug on MacOS where the window doesn't close

Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing OOI
None
Recognizing O

C:\Users\User\AppData\Local\Temp\ipykernel_188792\3156998007.py:18: RuntimeWarning: overflow encountered in ushort_scalars
  if (xref-x)**2+(yref-y)**2>maxdist**2:


2
None
[228 284  72]
1
None
2
None
[240 288  74]
[240 288  74]
[244 290  73]
[244 290  73]
[250 290  76]
[250 290  76]
[250 290  76]
[254 292  76]
[254 292  76]
1
None
[270 292  75]
[270 292  75]
[276 292  75]
[276 292  75]
[284 288  77]
[284 288  77]
[292 292  75]
[292 292  75]
[292 292  75]
[298 292  75]
[298 292  75]
1
None
[310 286  79]
[310 286  79]
1
None
2
None
3
None
4
None
5
None
6
None
7
None
[344 292  72]
[344 292  72]
[348 296  72]
[352 298  72]
[352 298  72]
[356 302  72]
[356 302  72]
[358 302  74]
[358 302  74]
[358 302  74]
[358 304  72]
[358 304  72]
[350 302  76]
[350 302  76]
1
None
2
None
3
None
4
None
5
None
6
None
7
None
8
None
9
None
10
None
11
Recognizing OOI
[288 302  75]
Tracking OOI
[280 302  76]
[276 300  76]
[276 300  76]
1
None
2
None
3
None
4
None
5
None
[264 302  75]
[264 302  75]
1
None
2
None
[254 300  75]
[250 300  75]
[250 300  75]
[244 300  74]
[244 300  74]
[244 300  74]
1
None
2
None
3
None
4
None
5
None
6
None
7
None
[230 304  45]
[230 304  45]
1

-1